# Generated by Django 3.1.4 on 2021-05-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_post_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='contact_phone',
            field=models.PositiveBigIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
